### ISSUE TITLE
cant view some tables of eosio system account

### ISSUE THREAD

**Issue by beac0n** [eoscafe/bloks-desktop#3]
To reproduce:
- visit https://bloks.io/account/eosio
- click "contract" => "contract tables" => "rammarket"

the console will print an error:
```
chunk-vendors.f321390d.js:63 TypeError: Cannot read property 'name' of undefined
    at a.tableKeyName (account.1785a450.js:7)
    at nr.get (chunk-vendors.f321390d.js:44)
    at nr.evaluate (chunk-vendors.f321390d.js:44)
    at a.tableKeyName (chunk-vendors.f321390d.js:44)
    at account.1785a450.js:7
    at a.Ie [as _l] (chunk-vendors.f321390d.js:44)
    at a (account.1785a450.js:7)
    at a.t._render (chunk-vendors.f321390d.js:44)
    at a.r (chunk-vendors.f321390d.js:44)
    at nr.get (chunk-vendors.f321390d.js:44)
    at nr.run (chunk-vendors.f321390d.js:44)
    at Kn (chunk-vendors.f321390d.js:44)
    at Array.<anonymous> (chunk-vendors.f321390d.js:44)
    at ce (chunk-vendors.f321390d.js:44)
(anonymous) @ chunk-vendors.f321390d.js:63
ie @ chunk-vendors.f321390d.js:44
re @ chunk-vendors.f321390d.js:44
ee @ chunk-vendors.f321390d.js:44
t._render @ chunk-vendors.f321390d.js:44
r @ chunk-vendors.f321390d.js:44
nr.get @ chunk-vendors.f321390d.js:44
nr.run @ chunk-vendors.f321390d.js:44
Kn @ chunk-vendors.f321390d.js:44
(anonymous) @ chunk-vendors.f321390d.js:44
ce @ chunk-vendors.f321390d.js:44
Promise.then (async)
oe @ chunk-vendors.f321390d.js:44
pe @ chunk-vendors.f321390d.js:44
tr @ chunk-vendors.f321390d.js:44
nr.update @ chunk-vendors.f321390d.js:44
mt.notify @ chunk-vendors.f321390d.js:44
set @ chunk-vendors.f321390d.js:44
rr.set @ chunk-vendors.f321390d.js:44
(anonymous) @ account.1785a450.js:7
c @ chunk-vendors.f321390d.js:68
(anonymous) @ chunk-vendors.f321390d.js:68
t.<computed> @ chunk-vendors.f321390d.js:68
o @ chunk-vendors.f321390d.js:50
s @ chunk-vendors.f321390d.js:50
Promise.then (async)
o @ chunk-vendors.f321390d.js:50
s @ chunk-vendors.f321390d.js:50
(anonymous) @ chunk-vendors.f321390d.js:50
e @ chunk-vendors.f321390d.js:50
(anonymous) @ chunk-vendors.f321390d.js:50
t @ account.1785a450.js:7
click @ account.1785a450.js:7
ne @ chunk-vendors.f321390d.js:44
n @ chunk-vendors.f321390d.js:44
Ji.o._wrapper @ chunk-vendors.f321390d.js:44
r @ chunk-vendors.f321390d.js:63
```

If I inspect the code, I see this function

```
                tableKeyName: function() {
                    var e = this;
                    if (!this.selectedTableInfo)
                        return null;
                    if (this.selectedTableInfo.key_names.length)
                        return this.selectedTableInfo.key_names[0];
                    var t = this.abi.structs.find(function(t) {
                        return t.name === e.selectedTableInfo.type
                    });
                    if (t && t.fields.length) {
                        var n = t.fields.find(function(e) {
                            return "i64" === e.type || "name" === e.type
                        });
                        return n.name
                    }
                    return null
                },
```

However, t.fields does not have the required type, so n will be undefined, what leas to the error.

A quickfix I found, was to use t.name instead of n.name.

So you could fix this issue with the following code:

```
                tableKeyName: function() {
                    var e = this;
                    if (!this.selectedTableInfo)
                        return null;
                    if (this.selectedTableInfo.key_names.length)
                        return this.selectedTableInfo.key_names[0];
                    var t = this.abi.structs.find(function(t) {
                        return t.name === e.selectedTableInfo.type
                    });
                    if (t && t.fields.length) {
                        var n = t.fields.find(function(e) {
                            return "i64" === e.type || "name" === e.type
                        });
                        return !!n ? n.name : t.name
                    }
                    return null
                },
```

**Comment by jafri** [comment]
Fixed.

On May 12, 2019, at 1:42 PM, Maximilian <notifications@github.com<mailto:notifications@github.com>> wrote:


To reproduce:

  *   visit https://bloks.io/account/eosio
  *   click "contract" => "contract tables" => "rammarket"

the console will print an error:

chunk-vendors.f321390d.js:63 TypeError: Cannot read property 'name' of undefined
    at a.tableKeyName (account.1785a450.js:7)
    at nr.get (chunk-vendors.f321390d.js:44)
    at nr.evaluate (chunk-vendors.f321390d.js:44)
    at a.tableKeyName (chunk-vendors.f321390d.js:44)
    at account.1785a450.js:7
    at a.Ie [as _l] (chunk-vendors.f321390d.js:44)
    at a (account.1785a450.js:7)
    at a.t._render (chunk-vendors.f321390d.js:44)
    at a.r (chunk-vendors.f321390d.js:44)
    at nr.get (chunk-vendors.f321390d.js:44)
    at nr.run (chunk-vendors.f321390d.js:44)
    at Kn (chunk-vendors.f321390d.js:44)
    at Array.<anonymous> (chunk-vendors.f321390d.js:44)
    at ce (chunk-vendors.f321390d.js:44)
(anonymous) @ chunk-vendors.f321390d.js:63
ie @ chunk-vendors.f321390d.js:44
re @ chunk-vendors.f321390d.js:44
ee @ chunk-vendors.f321390d.js:44
t._render @ chunk-vendors.f321390d.js:44
r @ chunk-vendors.f321390d.js:44
nr.get @ chunk-vendors.f321390d.js:44
nr.run @ chunk-vendors.f321390d.js:44
Kn @ chunk-vendors.f321390d.js:44
(anonymous) @ chunk-vendors.f321390d.js:44
ce @ chunk-vendors.f321390d.js:44
Promise.then (async)
oe @ chunk-vendors.f321390d.js:44
pe @ chunk-vendors.f321390d.js:44
tr @ chunk-vendors.f321390d.js:44
nr.update @ chunk-vendors.f321390d.js:44
mt.notify @ chunk-vendors.f321390d.js:44
set @ chunk-vendors.f321390d.js:44
rr.set @ chunk-vendors.f321390d.js:44
(anonymous) @ account.1785a450.js:7
c @ chunk-vendors.f321390d.js:68
(anonymous) @ chunk-vendors.f321390d.js:68
t.<computed> @ chunk-vendors.f321390d.js:68
o @ chunk-vendors.f321390d.js:50
s @ chunk-vendors.f321390d.js:50
Promise.then (async)
o @ chunk-vendors.f321390d.js:50
s @ chunk-vendors.f321390d.js:50
(anonymous) @ chunk-vendors.f321390d.js:50
e @ chunk-vendors.f321390d.js:50
(anonymous) @ chunk-vendors.f321390d.js:50
t @ account.1785a450.js:7
click @ account.1785a450.js:7
ne @ chunk-vendors.f321390d.js:44
n @ chunk-vendors.f321390d.js:44
Ji.o._wrapper @ chunk-vendors.f321390d.js:44
r @ chunk-vendors.f321390d.js:63


If I inspect the code, I see this function

                tableKeyName: function() {
                    var e = this;
                    if (!this.selectedTableInfo)
                        return null;
                    if (this.selectedTableInfo.key_names.length)
                        return this.selectedTableInfo.key_names[0];
                    var t = this.abi.structs.find(function(t) {
                        return t.name === e.selectedTableInfo.type
                    });
                    if (t && t.fields.length) {
                        var n = t.fields.find(function(e) {
                            return "i64" === e.type || "name" === e.type
                        });
                        return n.name
                    }
                    return null
                },


However, t.fields does not have the required type, so n will be undefined, what leas to the error.

A quickfix I found, was to use t.name instead of n.name.

So you could fix this issue with the following code:

                tableKeyName: function() {
                    var e = this;
                    if (!this.selectedTableInfo)
                        return null;
                    if (this.selectedTableInfo.key_names.length)
                        return this.selectedTableInfo.key_names[0];
                    var t = this.abi.structs.find(function(t) {
                        return t.name === e.selectedTableInfo.type
                    });
                    if (t && t.fields.length) {
                        var n = t.fields.find(function(e) {
                            return "i64" === e.type || "name" === e.type
                        });
                        return !!n ? n.name : t.name
                    }
                    return null
                },

**Comment by beac0n** [comment]
I can confirm that the bug is fixed.
